simple_api_app/urls.py
from django.urls import re_path

from . import views

app_name = 'simple_api_app'
urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^add_task/$', views.task, name='add_task'),
    re_path(r'^(?P<task_id>\d+)/edit_task/$', views.task, name='edit_task'),
    re_path(r'delete_task/(?P<pk>\d+)/$', views.TaskDeleteView.as_view(), name='delete_task'),
]

simpleapi/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from simple_api_app import views

router = routers.DefaultRouter()
router.register(r'tasks', views.TasksViewSet)
router.register(r'status', views.StatusViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('simpleapi/', include("simple_api_app.urls")),

    # web based API (with urls)
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # API calls
    path('api/statuses/', views.StatusList.as_view()),
    path('api/task_list/', views.TaskList.as_view()),
    path('api/task_list/<int:pk>/', views.TaskDetail.as_view()),

    # User management
    path('accounts/', include('django.contrib.auth.urls')),
]

simple_api_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Status(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

class Task(models.Model):
    title = models.CharField(
                    max_length=32, 
                    help_text='Title for the task')

    description = models.CharField(
                    max_length=256,
                    blank=True, default='', 
                    help_text='A longer description for the task (optional)')

    status = models.ForeignKey(
                    Status, 
                    on_delete=models.RESTRICT, 
                    help_text='The task status')

    due_date = models.DateTimeField(
                    help_text='When the task is due')

    user = models.ForeignKey(User, 
                            models.SET_NULL,
                            blank=True,
                            null=True)

    @property
    def due_date_in_the_past(self):
        return self.due_date <= timezone.now()

    def __str__(self):
        return self.title

simple_api_app/forms.py
from django import forms
from django.forms import fields
from .models import Task
from formset.widgets import DateTimeInput

class TaskForm(forms.ModelForm):

    due_date = fields.DateTimeField(
        widget=DateTimeInput
    )

    class Meta:
        model = Task
        fields = ['title', 'description', 'status', 'due_date']

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

simple_api_app/views.py
# Django imports
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import DeleteView
from django.views import generic
from django.db.models import Q
from django.core.paginator import (
    Paginator,
    EmptyPage,
    PageNotAnInteger,
)

# Django REST framework imports
from .serializers import TaskSerializerWeb, StatusSerializerWeb
from .serializers import TaskSerializerAPI, StatusSerializerAPI, TaskSerializerAPIEditStatus
from rest_framework import viewsets, status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.generics import ListAPIView

# internal imports
from .models import Task, Status
from .forms import TaskForm
from  .pagination import TaskListPagination

#
# FRONT END VIEWS
# 

# Show Tasks
@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'simple_api_app/index.html'
    context_object_name = 'task_list'

    def get_queryset(self):
        return Task.objects.filter(~Q(status__name='Done'), user=self.request.user).order_by("due_date")

# Add/Edit a Task
@login_required
def task(request, task_id=None):

    if "cancel" in request.POST:
        return HttpResponseRedirect(reverse('simple_api_app:index'))

    if task_id:
        task = get_object_or_404(Task, pk=task_id)

        # check someone isn't trying to just send a url to 
        # edit someone elses task
        if task.user != request.user:
            return HttpResponse('Unauthorized', status=401)
    else:
        task = Task()

    form = TaskForm(request.POST or None, instance=task)
    if request.POST:
        if form.is_valid():
            form.instance.user = request.user
            form.save()
        return HttpResponseRedirect(reverse('simple_api_app:index'))

    return render(request, "simple_api_app/task.html", {"form": form})

# Delete a Task
@method_decorator(login_required, name='dispatch')
class TaskDeleteView(DeleteView):

    model = Task
    success_url = reverse_lazy('simple_api_app:index')
    template_name = 'simple_api_app/delete_task.html'

    def post(self, request, *args, **kwargs):
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse('simple_api_app:index'))
        else:
            return super(TaskDeleteView, self).post(request, *args, **kwargs)

    def dispatch(self, *args, **kwargs):

        # Only allow deletion of a task belonging to logged in user
        task_instance = self.get_object()
        task_user = task_instance.user
        if task_user != self.request.user:
            return HttpResponse('Unauthorized', status=401)
        return super().dispatch(*args, **kwargs)

#
# DJANGO REST FRAMEWORK VIEWS
# 

# Django Rest Framework Web views

class TasksViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.order_by('id')
    serializer_class = TaskSerializerWeb

class StatusViewSet(viewsets.ModelViewSet):
    queryset = Status.objects.order_by('id')
    serializer_class = StatusSerializerWeb

# Django Rest Framework API calls (statuses)

class StatusList(APIView):
    # List of statuses
    def get(self, request, format=None):
        statuses = Status.objects.all()
        serializer = StatusSerializerAPI(statuses, many=True)
        return Response(serializer.data)

# Django Rest Framework API calls (tasks)

class TaskList(ListAPIView):

    pagination_class = TaskListPagination
    queryset = Task.objects.all().order_by("due_date")
    serializer_class = TaskSerializerAPI

    # Add task
    def post(self, request, format=None):
        serializer = TaskSerializerAPI(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class TaskDetail(APIView):
    # helper method
    def get_task(self, pk):
        try:
            return Task.objects.get(pk=pk)
        except Task.DoesNotExist:
            raise Http404

    # get a task
    def get(self, request, pk, format=None):
        task = self.get_task(pk)
        serializer = TaskSerializerAPI(task)
        return Response(serializer.data)

    # update a task
    def put(self, request, pk, format=None):
        task = self.get_task(pk)
        serializer = TaskSerializerAPIEditStatus(task, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    # delete a task
    def delete(self, request, pk, format=None):
        task = self.get_task(pk)
        task.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

simple_api_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Simple API App{% endblock %}</title>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/2.3.2/css/dataTables.dataTables.css" />
  
    <script src="https://cdn.datatables.net/2.3.2/js/dataTables.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="/static/simple_api_app/style.css" type="text/css" media="screen" />

    <script>
    $(document).ready( function () {
        // intialise datatable
        // - buttons column should not be sortable
        // - keep ordering by date
        $('#tasks').DataTable({
                        columnDefs: [{ orderable: false, targets: 4 }], 
                        order: []
                    });

        var table = $('#tasks').DataTable();
        
        table.columns().flatten().each( function ( colIdx ) {
            // Create the select list and search operation
            var select = $('<select />')
                .appendTo(
                    table.column(colIdx).footer()
                )
                .on( 'change', function () {
                    table
                        .column( colIdx )
                        .search( $(this).val() )
                        .draw();
                } );
        
            // Get the search data for the first column and add to the select list
            table
                .column( colIdx )
                .cache( 'search' )
                .sort()
                .unique()
                .each( function ( d ) {
                    select.append( $('<option value="'+d+'">'+d+'</option>') );
                } );
        } );
    } );
    </script>
</head>

<body>
    <div id="page" class="container">
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-sm"></div>
                    <div class="col-sm">
                        <h1>TASK&nbsp;MANAGEMENT</h1>
                    </div>
                    <div class="col-sm">
                    {% if user.is_authenticated %}
                        <div class="row">
                            <div class="col text-right">
                                <div class="username">User: {{ user.username }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col text-right">
                                <form action="{% url 'logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary btn-sm">Log Out</button>
                                </form>
                            </div>
                        </div>
                    {% endif %}
                    </div>
                </div>
            </div>
            <nav>{% block navigation %}{% endblock %}</nav>
        </header>
        <section>
            <div id="container">
            {% block content %}{% endblock %}
            </div>
        </section>
        <footer>
            {% block footer %}{% endblock %}
        </footer>
    </div>
</body>
</html>

simple_api_app/templates/simple_api_app/delete_task.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
<div class="d-flex justify-content-center">
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete the task with title <strong>{{ task.title }}</strong> ?</p>
        <div class="d-flex justify-content-center">
            <input type="submit" value="Delete" class="btn btn-danger btn-margin-right" />
            <input type="submit" name="cancel" value="Cancel" class="btn btn-default"/>
        </div>
    </form>
</div>
{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
{% endif %}

{% endblock %}

simple_api_app/templates/simple_api_app/index.html
{% extends "base.html" %}

{% block navigation %}

{% if user.is_authenticated %}

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'simple_api_app:index' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'simple_api_app:add_task' %}">Add a task</a>
    </li>
</ul>

{% endif %}

{% endblock %}

{% block content %}

{% if user.is_authenticated %}

    {% if task_list %}
        <table class="table" id="tasks">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Status</th>
                    <th scope="col">Due Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        {% for task in task_list %}
                <tr {% if task.due_date_in_the_past %}class="overdue"{% endif %}>
                    <td>{{ task.title }}</td>
                    <td>{{ task.description }}</td>
                    <td>{{ task.status }}</td>
                    <td>{{ task.due_date }}</td>
                    <td>
                        <div class="btn-group">
                            <form action="{% url 'simple_api_app:edit_task' task.id %}" method="get">
                                <input type="submit" value="Edit" class="btn btn-warning btn--margin-right">
                            </form>
                            <form action="{% url 'simple_api_app:delete_task' task.id %}" method="get">
                                <input type="submit" value="Delete" class="btn btn-danger">
                            </form>
                        </div>
                    </td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="row">
            <div class="col-xs-12">
                There are no tasks yet.
            </div>
        </div>
    {% endif %}

{% else %}
<div class="d-flex justify-content-center" >
    <div class="d-flex align-items-center" style="height: 180px;">
        <a href="{% url 'login' %}">Please Log In</a>
    </div>
</div>
{% endif %}

{% endblock %}

{% block footer %}

{% if user.is_authenticated %}

{% if task_list.has_other_pages %}
<div class="btn-group" role="group" aria-label="Item pagination">
    {% if task_list.has_previous %}
        <a href="?page={{ items_page.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
    {% endif %}

    {% for page_number in task_list.paginator.page_range %}
        {% if task_list.number == page_number %}
            <button class="btn btn-outline-primary active">
                <span>{{ page_number }} <span class="sr-only">(current)</span></span>
            </button>
        {% else %}
            <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                {{ page_number }}
            </a>
        {% endif %}
    {% endfor %}

    {% if task_list.has_next %}
        <a href="?page={{ task_list.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
    {% endif %}
</div>
{% endif %}

{% endif %}

{% endblock %}

simple_api_app/templates/simple_api_app/task.html
{% extends "base.html" %}

{% block navigation %}

{% if user.is_authenticated %}

<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'simple_api_app:index' %}">Home</a>
    </li>
</ul>

{% endif %}

{% endblock %}

{% block content %}

{% if user.is_authenticated %}

<form action="" method="post">{% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
        <p>{{field}}</p>
        <small id="{{ field.name }}Help" class="form-text text-muted">{{field.help_text}}</small>
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    {% endfor %}

    <div class="btn-group">
    <input type="submit" value="Submit" class="btn btn-primary btn--margin-right">
</form>

    <form action="" method="post" novalidate>{% csrf_token %}
        <input type="submit" name=cancel value="Cancel" class="btn">
    </form>
    </div>

{% else %}

    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>

{% endif %}

{% endblock %}